# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: '20.x'
  appDirectory: 'LogicaPura'

steps:
  - task: UseNode@1
    inputs:
      version: $(nodeVersion)
    displayName: 'Instalar Node.js'

  - script: |
      cd $(appDirectory)
      npm ci
    displayName: 'Instalar dependências'

  - script: |
      cd $(appDirectory)
      npm run test
    displayName: 'Rodar testes automatizados'

  - script: |
      cd $(appDirectory)
      npm run build
    displayName: 'Gerar build'