trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Definimos aqui o caminho da pasta para não precisar repetir toda hora
  projectFolder: 'LogicaPura'

steps:
# 1. Instalar Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Instalar Node.js'

# 2. Cache (Ajustado para olhar o package-lock dentro da subpasta)
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(projectFolder)/package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
    path: $(Build.SourcesDirectory)/$(projectFolder)/node_modules
  displayName: 'Gerenciar Cache do NPM'

# 3. Instalar dependências (Entrando na pasta LogicaPura)
- script: |
    npm install
  workingDirectory: $(projectFolder)
  displayName: 'Instalar dependências'

# 4. Rodar o Build (Entrando na pasta LogicaPura)
- script: |
    npm run build
  workingDirectory: $(projectFolder)
  displayName: 'Executar Build do Vite'

# 5. Publicar Artefatos (A pasta dist estará dentro de LogicaPura)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(projectFolder)/dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publicar Artefatos'