trigger:
- main  

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '24.14.1' 
  displayName: 'Instalar Node.js'


- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
    path: $(Build.SourcesDirectory)/node_modules
  displayName: 'Gerenciar Cache do NPM'


- script: |
    npm install
  displayName: 'Instalar dependências (NPM Install)'


- script: |
    npm run build
  displayName: 'Executar Build do Projeto'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publicar Artefatos do Build'